using System.Collections;
using UnityEngine;

public class GameManager : MonoBehaviour
{
    public static GameManager Instance;
    [SerializeField] private DunGen _dungeonGenerator;
    [SerializeField] private CharacterSheet _player;

    //the grid generated by DunGen, passed here before GameReady is true
    public GameTile[,] FinalGrid { get; private set; }

    public bool GameReady { get; private set; }

    void Awake()
    {
        if (Instance != null)
        {
            Destroy(Instance);
        }

        Instance = this;
    }

    IEnumerator Start()
    {
        _dungeonGenerator.GenerateDungeon();

        while (ValidateGameReady() == false)
        {
            yield return null;
        }
        FinalGrid = _dungeonGenerator.Grid;
        if (_player == null)
        {
            Debug.LogError("player null");
        }
        _player.gameObject.transform.position = _dungeonGenerator.PlayerSpawnPosition;
        _player.CurrentTile = _dungeonGenerator.PlayerStartTile;
        _dungeonGenerator.PlayerStartTile.IsOccupied = true;
        _dungeonGenerator.PlayerStartTile.OccupiedBy = _player;
        Debug.Log($"Player starts at grid position with floor: {_player.CurrentTile.IsFloor}");
    }

    private bool ValidateGameReady()
    {
        if (_dungeonGenerator.DungeonGenerated)
        {
            return GameReady = true;
        }

        return false;
    }
}
